language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
services:
- docker
script:
# 1.4.4 and 1.5.4 do not seem to support ubuntu:16.0
- >
  wget -O- bit.ly/ansibletest | env
  DOCKER_IMAGES="ubuntu:12.04 ubuntu:14.04 ubuntu:16.04
  debian:8 fedora:20 fedora:24"
  ANSIBLE_VERSIONS="1.4.4"
  sh
- >
  wget -O- bit.ly/ansibletest | env
  DOCKER_IMAGES="ubuntu:12.04 ubuntu:14.04 ubuntu:16.04 ubuntu:16.10
  debian:8 fedora:20 fedora:24"
  ANSIBLE_VERSIONS="1.9.2 2.1.0.0"
  sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: u9B1teQJKu0GNDmfwQWN9bCg+L8HhyuSbAQ1rrIGHKr5cdeTMyr9n7HZeBMf0Arfdrehz8WiCAEULzqtE7HMkZUCDHacaB/rz9a1adE8D0gFClI6UiFOqj30enXXHl6Xba03fAUSMI1e/pN8iz+mDMG8G3D3VBIOXPJpPF9cx6IsUvGUr1UXaXE+8Y2IJmwhu7nmY/uFaHZJqm4Cj9wGYLGX9/SYLgtTGs6YUkmf+h6Osa639UER+pt1dfJzLTKTVXInXxGEXPnxt+i4MxSFmruxh3eDc5NzAnHK1HUkN2T4VMU20G5KabZXdyviqRetm2G3DExzS75GS/Gck1fwcuvXmu+KX1wmQo6VVydMjE8FkyW42O4bAbirhnJ1vziKpWEkPD214tCmbzn46yW/kwyoAKMEd3zzocOx3hFbcXHDEo6QaibUusVwTRUUHxtQKu1rJDCGuOZncdG6ukBDpWyPAm/tZ/rdiBXBHBYL/y7/aR6fk4O2a4oWCSsTwOTLD2HK0qdpGy1AE2pRKXTDTE2tP1aiDYE7JlEnwxEkRHrooUSHmcvLzm08FyoH0zd2d4wsuNBUy6TXU55azuX9YPLdUJLjafWs1FJU8UD7A330faSDE4AupQOfEjoVcSrG34MQmMN5R49cae21Vd2343VjP8iR0Jx7AgTNmrvFIQM=
  email:
    recipients:
      secure: r2v+f0b/mP3SkkRpvMI32mO8WjOXOG5zaI5vvoNb+zEd5prqGLayFFdba+xLFxtsnadLfxkEHcW8ppA/vauHHwSI7YqjHy15kVhJsZ1r7bmSALMoGnDYipyzjYcTOw215zGVoBSaGyCxg545zfbS4vUwSNYvJ3cgkCZLSBvc0ecyhn+U/LQZ85sbg8oy18GFjsOUWrE727WTzmj7+P6/Oj4iQV0A7VQlVp4FwlQu0BfitvI/K9DialwY0Swj1mJAMEfnpTn1DqzqjNW6Lj916R9zBpzNt3oMlmB8h/wVGd/SZ8AzBCURnKbvwr+h1t6dLZ7e2bsmdzQyfWx3e/51bZ5qxmB5SSNs1lutrkIsGTs/33MCU9VYqlbkb5U+hB6LXLL89Pwy0FpzG3IWBfUefo/52xQcW8Tx5kONlRUq25R3EJNJ4lye/H7ZqzDP9NPJF77sILRhBhk3qW0hTeuTT/HQLDRqmLRH4brMco0QvXy8hUHnZPm3x7T1VcabR7wLN5u5KOTtxGQ2689IezJgbVjrS85emz3z0314M8pUtCrcq/AUdNOVr5FNuEjigpeT1xu1cIDdMp7gVzTI7CkAvaI287nTDPQ8XQ3xQTPnzPAZsCvw51N5twth1vegIdJWW3fWO0SkpuKCLu1AyMnjOLc3x8OW6hI7bnMcyXTXPZ4=
